import 'package:flutter/widgets.dart';

/// Finance modul — BA (default) i EN stringovi (bez generičkog skraćivanja naziva modula).
class FinanceStrings {
  FinanceStrings._();

  static bool isEnglish(BuildContext context) {
    return Localizations.localeOf(context).languageCode == 'en';
  }

  static String t(BuildContext context, String key) {
    final en = isEnglish(context);
    final map = en ? _en : _bs;
    return map[key] ?? key;
  }

  static const _bs = <String, String>{
    'finance_hub_title': 'Finance',
    'finance_hub_subtitle':
        'Operativni novčani tok — računi, kategorije i transakcije (Callable sloj).',
    'card_accounts_title': 'Računi',
    'card_accounts_subtitle':
        'Bankovni računi, blagajne i trenutno stanje novca.',
    'card_categories_title': 'Cash Flow kategorije',
    'card_categories_subtitle':
        'Šifrarnik kategorija za operativne, investicione i finansijske tokove.',
    'module_not_enabled':
        'Modul finance_controlling nije uključen za ovu kompaniju.',
    'access_denied': 'Nemate pravo pristupa Finance modulu.',
    'accounts_title': 'Računi i blagajne',
    'accounts_empty': 'Nema evidentiranih računa.',
    'account_new': 'Novi račun',
    'account_edit': 'Uredi račun',
    'account_code': 'Šifra računa',
    'account_name': 'Naziv',
    'account_type': 'Vrsta računa',
    'currency': 'Valuta',
    'opening_balance': 'Početno stanje',
    'current_balance': 'Trenutno stanje',
    'bank_name': 'Banka',
    'iban': 'IBAN',
    'plant_key': 'Pogon',
    'active': 'Aktivan',
    'inactive': 'Neaktivan',
    'deactivate_account': 'Deaktiviraj račun',
    'deactivate_account_confirm':
        'Račun više neće biti dostupan za nove transakcije. Nastaviti?',
    'save': 'Spremi',
    'cancel': 'Odustani',
    'refresh': 'Osvježi',
    'categories_title': 'Cash Flow kategorije',
    'categories_empty': 'Nema kategorija.',
    'category_new': 'Nova kategorija',
    'category_edit': 'Uredi kategoriju',
    'category_code': 'Šifra kategorije',
    'category_name': 'Naziv kategorije',
    'activity_type': 'Vrsta aktivnosti',
    'activity_operating': 'Operativna aktivnost',
    'activity_investing': 'Investiciona aktivnost',
    'activity_financing': 'Finansijska aktivnost',
    'sort_order': 'Redoslijed',
    'deactivate_category': 'Deaktiviraj kategoriju',
    'deactivate_category_confirm': 'Kategorija više neće biti dostupna za nove unose. Nastaviti?',
    'filter_active_only': 'Samo aktivne',
    'type_transactional': 'Transakcijski račun',
    'type_foreign_currency': 'Devizni račun',
    'type_cash_register': 'Blagajna',
    'type_virtual': 'Virtualni račun',
    'type_credit_line': 'Kreditni račun',
    'error_generic': 'Došlo je do greške. Pokušajte ponovo.',
    'saved': 'Spremljeno.',
    'deactivated': 'Deaktivirano.',
    'pick_date': 'Odaberi datum',
    'card_transactions_title': 'Transakcije',
    'card_transactions_subtitle':
        'Nacrti, knjiženje, usklađivanje i storno operativnih novčanih tokova.',
    'card_realized_title': 'Realizovani Cash Flow',
    'card_realized_subtitle':
        'Sažetak knjiženih i usklađenih transakcija za odabrani period.',
    'transactions_title': 'Transakcije',
    'transactions_empty': 'Nema transakcija za odabrane filtere.',
    'transaction_new': 'Nova transakcija',
    'transaction_edit': 'Uredi nacrt',
    'transaction_detail': 'Detalji transakcije',
    'transaction_code': 'Šifra transakcije',
    'transaction_date': 'Datum transakcije',
    'value_date': 'Datum valute',
    'amount': 'Iznos',
    'direction': 'Smjer',
    'direction_inflow': 'Priliv',
    'direction_outflow': 'Odliv',
    'status': 'Status',
    'tx_status_draft': 'Nacrt',
    'tx_status_planned': 'Planirano',
    'tx_status_posted': 'Knjiženo',
    'tx_status_reconciled': 'Usklađeno',
    'tx_status_cancelled': 'Otkazano',
    'description': 'Opis',
    'reference': 'Referenca',
    'filter_status': 'Status',
    'filter_account': 'Račun',
    'filter_direction': 'Smjer',
    'filter_period': 'Period',
    'filter_all': 'Svi',
    'filter_all_accounts': 'Svi računi',
    'date_from': 'Datum od',
    'date_to': 'Datum do',
    'account': 'Račun',
    'category': 'Kategorija',
    'post_transaction': 'Knjiži',
    'post_transaction_confirm':
        'Knjiženje mijenja saldo računa. Nastaviti?',
    'reconcile_transaction': 'Uskladi',
    'reconcile_transaction_confirm':
        'Usklađivanje ne mijenja saldo računa. Nastaviti?',
    'reverse_transaction': 'Storniraj',
    'reverse_transaction_confirm':
        'Storno kreira novu transakciju suprotnog smjera. Original ostaje u historiji. Nastaviti?',
    'cancel_draft': 'Otkaži nacrt',
    'cancel_draft_confirm': 'Nacrt će biti otkazan bez promjene salda. Nastaviti?',
    'posted': 'Knjiženo.',
    'reconciled': 'Usklađeno.',
    'reversed': 'Storno izvršen.',
    'draft_cancelled': 'Nacrt otkazan.',
    'audit_section': 'Revizija',
    'audit_created_by': 'Kreirao',
    'audit_posted_by': 'Knjižio',
    'audit_reconciled_by': 'Uskladio',
    'audit_posted_at': 'Knjiženo',
    'audit_reconciled_at': 'Usklađeno',
    'link_reversal': 'Storno transakcija',
    'link_original': 'Originalna transakcija',
    'realized_title': 'Realizovani Cash Flow',
    'realized_period': 'Period',
    'realized_total_inflows': 'Ukupni prilivi',
    'realized_total_outflows': 'Ukupni odlivi',
    'realized_net_cash_flow': 'Neto novčani tok',
    'realized_closing_balance': 'Završno stanje',
    'realized_transaction_count': 'Broj transakcija',
    'realized_by_activity': 'Po vrsti aktivnosti',
    'realized_inflows': 'Prilivi',
    'realized_outflows': 'Odlivi',
    'realized_net': 'Neto',
    'load_report': 'Učitaj izvještaj',
    'select_account': 'Odaberi račun',
    'select_category': 'Odaberi kategoriju',
    'select_direction': 'Odaberi smjer',
  };

  static const _en = <String, String>{
    'finance_hub_title': 'Finance',
    'finance_hub_subtitle':
        'Operational cash flow — accounts, categories and transactions (Callable layer).',
    'card_accounts_title': 'Accounts',
    'card_accounts_subtitle':
        'Bank accounts, cash registers and current cash balance.',
    'card_categories_title': 'Cash Flow categories',
    'card_categories_subtitle':
        'Category catalog for operating, investing and financing flows.',
    'module_not_enabled':
        'The finance_controlling module is not enabled for this company.',
    'access_denied': 'You do not have access to the Finance module.',
    'accounts_title': 'Accounts and cash registers',
    'accounts_empty': 'No accounts recorded.',
    'account_new': 'New account',
    'account_edit': 'Edit account',
    'account_code': 'Account code',
    'account_name': 'Name',
    'account_type': 'Account type',
    'currency': 'Currency',
    'opening_balance': 'Opening balance',
    'current_balance': 'Current balance',
    'bank_name': 'Bank',
    'iban': 'IBAN',
    'plant_key': 'Plant',
    'active': 'Active',
    'inactive': 'Inactive',
    'deactivate_account': 'Deactivate account',
    'deactivate_account_confirm':
        'The account will no longer be available for new transactions. Continue?',
    'save': 'Save',
    'cancel': 'Cancel',
    'refresh': 'Refresh',
    'categories_title': 'Cash Flow categories',
    'categories_empty': 'No categories.',
    'category_new': 'New category',
    'category_edit': 'Edit category',
    'category_code': 'Category code',
    'category_name': 'Category name',
    'activity_type': 'Activity type',
    'activity_operating': 'Operating activity',
    'activity_investing': 'Investing activity',
    'activity_financing': 'Financing activity',
    'sort_order': 'Sort order',
    'deactivate_category': 'Deactivate category',
    'deactivate_category_confirm':
        'The category will no longer be available for new entries. Continue?',
    'filter_active_only': 'Active only',
    'type_transactional': 'Transactional account',
    'type_foreign_currency': 'Foreign currency account',
    'type_cash_register': 'Cash register',
    'type_virtual': 'Virtual account',
    'type_credit_line': 'Credit line',
    'error_generic': 'Something went wrong. Please try again.',
    'saved': 'Saved.',
    'deactivated': 'Deactivated.',
    'pick_date': 'Pick date',
    'card_transactions_title': 'Transactions',
    'card_transactions_subtitle':
        'Drafts, posting, reconciliation and reversal of operational cash flows.',
    'card_realized_title': 'Realized Cash Flow',
    'card_realized_subtitle':
        'Summary of posted and reconciled transactions for the selected period.',
    'transactions_title': 'Transactions',
    'transactions_empty': 'No transactions for the selected filters.',
    'transaction_new': 'New transaction',
    'transaction_edit': 'Edit draft',
    'transaction_detail': 'Transaction details',
    'transaction_code': 'Transaction code',
    'transaction_date': 'Transaction date',
    'value_date': 'Value date',
    'amount': 'Amount',
    'direction': 'Direction',
    'direction_inflow': 'Inflow',
    'direction_outflow': 'Outflow',
    'status': 'Status',
    'tx_status_draft': 'Draft',
    'tx_status_planned': 'Planned',
    'tx_status_posted': 'Posted',
    'tx_status_reconciled': 'Reconciled',
    'tx_status_cancelled': 'Cancelled',
    'description': 'Description',
    'reference': 'Reference',
    'filter_status': 'Status',
    'filter_account': 'Account',
    'filter_direction': 'Direction',
    'filter_period': 'Period',
    'filter_all': 'All',
    'filter_all_accounts': 'All accounts',
    'date_from': 'Date from',
    'date_to': 'Date to',
    'account': 'Account',
    'category': 'Category',
    'post_transaction': 'Post',
    'post_transaction_confirm':
        'Posting changes the account balance. Continue?',
    'reconcile_transaction': 'Reconcile',
    'reconcile_transaction_confirm':
        'Reconciliation does not change the account balance. Continue?',
    'reverse_transaction': 'Reverse',
    'reverse_transaction_confirm':
        'Reversal creates a new transaction in the opposite direction. The original remains in history. Continue?',
    'cancel_draft': 'Cancel draft',
    'cancel_draft_confirm':
        'The draft will be cancelled without changing the balance. Continue?',
    'posted': 'Posted.',
    'reconciled': 'Reconciled.',
    'reversed': 'Reversal completed.',
    'draft_cancelled': 'Draft cancelled.',
    'audit_section': 'Audit trail',
    'audit_created_by': 'Created by',
    'audit_posted_by': 'Posted by',
    'audit_reconciled_by': 'Reconciled by',
    'audit_posted_at': 'Posted at',
    'audit_reconciled_at': 'Reconciled at',
    'link_reversal': 'Reversal transaction',
    'link_original': 'Original transaction',
    'realized_title': 'Realized Cash Flow',
    'realized_period': 'Period',
    'realized_total_inflows': 'Total inflows',
    'realized_total_outflows': 'Total outflows',
    'realized_net_cash_flow': 'Net cash flow',
    'realized_closing_balance': 'Closing balance',
    'realized_transaction_count': 'Transaction count',
    'realized_by_activity': 'By activity type',
    'realized_inflows': 'Inflows',
    'realized_outflows': 'Outflows',
    'realized_net': 'Net',
    'load_report': 'Load report',
    'select_account': 'Select account',
    'select_category': 'Select category',
    'select_direction': 'Select direction',
  };
}
