import 'package:flutter/widgets.dart';

/// Finance modul — BA (default) i EN stringovi (bez generičkog skraćivanja naziva modula).
class FinanceStrings {
  FinanceStrings._();

  static bool isEnglish(BuildContext context) {
    return Localizations.localeOf(context).languageCode == 'en';
  }

  static String t(BuildContext context, String key) {
    final en = isEnglish(context);
    final map = en ? _en : _bs;
    return map[key] ?? key;
  }

  static const _bs = <String, String>{
    'finance_hub_title': 'Finance',
    'finance_hub_subtitle':
        'Operativni novčani tok — računi, kategorije i transakcije (Callable sloj).',
    'card_accounts_title': 'Računi',
    'card_accounts_subtitle':
        'Bankovni računi, blagajne i trenutno stanje novca.',
    'card_categories_title': 'Cash Flow kategorije',
    'card_categories_subtitle':
        'Šifrarnik kategorija za operativne, investicione i finansijske tokove.',
    'module_not_enabled':
        'Modul finance_controlling nije uključen za ovu kompaniju.',
    'access_denied': 'Nemate pravo pristupa Finance modulu.',
    'accounts_title': 'Računi i blagajne',
    'accounts_empty': 'Nema evidentiranih računa.',
    'account_new': 'Novi račun',
    'account_edit': 'Uredi račun',
    'account_code': 'Šifra računa',
    'account_name': 'Naziv',
    'account_type': 'Vrsta računa',
    'currency': 'Valuta',
    'opening_balance': 'Početno stanje',
    'current_balance': 'Trenutno stanje',
    'bank_name': 'Banka',
    'iban': 'IBAN',
    'plant_key': 'Pogon',
    'active': 'Aktivan',
    'inactive': 'Neaktivan',
    'deactivate_account': 'Deaktiviraj račun',
    'deactivate_account_confirm':
        'Račun više neće biti dostupan za nove transakcije. Nastaviti?',
    'save': 'Spremi',
    'cancel': 'Odustani',
    'refresh': 'Osvježi',
    'categories_title': 'Cash Flow kategorije',
    'categories_empty': 'Nema kategorija.',
    'category_new': 'Nova kategorija',
    'category_edit': 'Uredi kategoriju',
    'category_code': 'Šifra kategorije',
    'category_name': 'Naziv kategorije',
    'activity_type': 'Vrsta aktivnosti',
    'activity_operating': 'Operativna aktivnost',
    'activity_investing': 'Investiciona aktivnost',
    'activity_financing': 'Finansijska aktivnost',
    'sort_order': 'Redoslijed',
    'deactivate_category': 'Deaktiviraj kategoriju',
    'deactivate_category_confirm': 'Kategorija više neće biti dostupna za nove unose. Nastaviti?',
    'filter_active_only': 'Samo aktivne',
    'type_transactional': 'Transakcijski račun',
    'type_foreign_currency': 'Devizni račun',
    'type_cash_register': 'Blagajna',
    'type_virtual': 'Virtualni račun',
    'type_credit_line': 'Kreditni račun',
    'error_generic': 'Došlo je do greške. Pokušajte ponovo.',
    'saved': 'Spremljeno.',
    'deactivated': 'Deaktivirano.',
    'pick_date': 'Odaberi datum',
    'card_transactions_title': 'Transakcije',
    'card_transactions_subtitle':
        'Nacrti, knjiženje, usklađivanje i storno operativnih novčanih tokova.',
    'card_realized_title': 'Realizovani Cash Flow',
    'card_realized_subtitle':
        'Sažetak knjiženih i usklađenih transakcija za odabrani period.',
    'transactions_title': 'Transakcije',
    'transactions_empty': 'Nema transakcija za odabrane filtere.',
    'transaction_new': 'Nova transakcija',
    'transaction_edit': 'Uredi nacrt',
    'transaction_detail': 'Detalji transakcije',
    'transaction_code': 'Šifra transakcije',
    'transaction_date': 'Datum transakcije',
    'value_date': 'Datum valute',
    'amount': 'Iznos',
    'direction': 'Smjer',
    'direction_inflow': 'Priliv',
    'direction_outflow': 'Odliv',
    'status': 'Status',
    'tx_status_draft': 'Nacrt',
    'tx_status_planned': 'Planirano',
    'tx_status_posted': 'Knjiženo',
    'tx_status_reconciled': 'Usklađeno',
    'tx_status_cancelled': 'Otkazano',
    'description': 'Opis',
    'reference': 'Referenca',
    'filter_status': 'Status',
    'filter_account': 'Račun',
    'filter_direction': 'Smjer',
    'filter_period': 'Period',
    'filter_all': 'Svi',
    'filter_all_accounts': 'Svi računi',
    'date_from': 'Datum od',
    'date_to': 'Datum do',
    'account': 'Račun',
    'category': 'Kategorija',
    'post_transaction': 'Knjiži',
    'post_transaction_confirm':
        'Knjiženje mijenja saldo računa. Nastaviti?',
    'reconcile_transaction': 'Uskladi',
    'reconcile_transaction_confirm':
        'Usklađivanje ne mijenja saldo računa. Nastaviti?',
    'reverse_transaction': 'Storniraj',
    'reverse_transaction_confirm':
        'Storno kreira novu transakciju suprotnog smjera. Original ostaje u historiji. Nastaviti?',
    'cancel_draft': 'Otkaži nacrt',
    'cancel_draft_confirm': 'Nacrt će biti otkazan bez promjene salda. Nastaviti?',
    'posted': 'Knjiženo.',
    'reconciled': 'Usklađeno.',
    'reversed': 'Storno izvršen.',
    'draft_cancelled': 'Nacrt otkazan.',
    'audit_section': 'Revizija',
    'audit_created_by': 'Kreirao',
    'audit_posted_by': 'Knjižio',
    'audit_reconciled_by': 'Uskladio',
    'audit_posted_at': 'Knjiženo',
    'audit_reconciled_at': 'Usklađeno',
    'link_reversal': 'Storno transakcija',
    'link_original': 'Originalna transakcija',
    'realized_title': 'Realizovani Cash Flow',
    'realized_period': 'Period',
    'realized_total_inflows': 'Ukupni prilivi',
    'realized_total_outflows': 'Ukupni odlivi',
    'realized_net_cash_flow': 'Neto novčani tok',
    'realized_closing_balance': 'Završno stanje',
    'realized_transaction_count': 'Broj transakcija',
    'realized_by_activity': 'Po vrsti aktivnosti',
    'realized_inflows': 'Prilivi',
    'realized_outflows': 'Odlivi',
    'realized_net': 'Neto',
    'load_report': 'Učitaj izvještaj',
    'select_account': 'Odaberi račun',
    'select_category': 'Odaberi kategoriju',
    'select_direction': 'Odaberi smjer',
    'invoices_hub_subtitle':
        'Fakture, potraživanja i obaveze — Callable sloj (P2).',
    'card_sales_invoices_title': 'Izlazne fakture',
    'card_sales_invoices_subtitle':
        'Nacrti, izdavanje i pregled potraživanja po fakturi.',
    'card_purchase_invoices_title': 'Ulazne fakture',
    'card_purchase_invoices_subtitle':
        'Nacrti, odobravanje i pregled obaveza po fakturi.',
    'card_receivables_title': 'Potraživanja',
    'card_receivables_subtitle':
        'Otvorene i djelimično plaćene izlazne fakture.',
    'card_payables_title': 'Obaveze',
    'card_payables_subtitle':
        'Otvorene i djelimično plaćene ulazne fakture.',
    'sales_invoices_title': 'Izlazne fakture',
    'sales_invoices_empty': 'Nema izlaznih faktura.',
    'sales_invoice_new': 'Nova izlazna faktura',
    'sales_invoice_edit': 'Uredi nacrt izlazne fakture',
    'purchase_invoices_title': 'Ulazne fakture',
    'purchase_invoices_empty': 'Nema ulaznih faktura.',
    'purchase_invoice_new': 'Nova ulazna faktura',
    'purchase_invoice_edit': 'Uredi nacrt ulazne fakture',
    'receivables_title': 'Potraživanja',
    'receivables_empty': 'Nema otvorenih potraživanja.',
    'receivables_open_list': 'Otvorene i djelimično plaćene fakture',
    'payables_title': 'Obaveze',
    'payables_empty': 'Nema otvorenih obaveza.',
    'payables_open_list': 'Otvorene i djelimično plaćene obaveze',
    'customer_id': 'Šifra kupca',
    'customer_name': 'Kupac',
    'supplier_id': 'Šifra dobavljača',
    'supplier_name': 'Dobavljač',
    'net_amount': 'Neto iznos',
    'tax_amount': 'PDV iznos',
    'total_amount': 'Ukupan iznos',
    'paid_amount': 'Plaćeno',
    'open_amount': 'Otvoreno',
    'issue_date': 'Datum izdavanja',
    'due_date': 'Datum dospijeća',
    'issue_sales_invoice': 'Izdaj fakturu',
    'approve_purchase_invoice': 'Odobri fakturu',
    'cancel_invoice': 'Otkaži fakturu',
    'cancel_invoice_confirm':
        'Faktura će biti otkazana prema pravilima backend lifecycle-a. Nastaviti?',
    'invoice_issued': 'Faktura je izdana.',
    'invoice_approved': 'Faktura je odobrena.',
    'invoice_cancelled': 'Faktura je otkazana.',
    'invoice_overdue': 'Dospjelo',
    'invoice_erp_synced': 'ERP',
    'invoice_erp_readonly_hint':
        'ERP-sinhronizovana faktura: ERP polja nisu ručno promjenjiva.',
    'open_items_count': 'Broj otvorenih faktura',
    'open_items_total': 'Ukupan otvoreni iznos',
    'open_items_overdue_count': 'Broj dospjelih faktura',
    'open_items_overdue_amount': 'Dospjeli iznos',
    'inv_status_draft': 'Nacrt',
    'inv_status_open': 'Otvoreno',
    'inv_status_partial': 'Djelimično plaćeno',
    'inv_status_paid': 'Plaćeno',
    'inv_status_cancelled': 'Otkazano',
    'allocate_to_invoices': 'Alociraj na fakture',
    'allocated_amount': 'Alocirano',
    'unallocated_amount': 'Nealocirano',
    'payment_allocations_section': 'Alokacije plaćanja',
    'allocations_empty': 'Nema alokacija.',
    'allocations_active_total': 'Ukupno aktivno alocirano',
    'allocation_add_invoice': 'Dodaj fakturu',
    'allocation_lines_empty': 'Dodajte jednu ili više faktura za alokaciju.',
    'allocation_line_amount': 'Iznos alokacije',
    'allocation_invoice_remaining': 'Preostali otvoreni iznos fakture',
    'allocation_batch_total': 'Zbir alokacija',
    'allocation_remaining_tx': 'Preostali nealocirani iznos transakcije',
    'allocation_confirm': 'Potvrdi alokaciju',
    'allocation_saved': 'Alokacija je spremljena.',
    'allocation_no_invoices': 'Nema odgovarajućih otvorenih faktura.',
    'allocation_pick_sales_invoice': 'Odaberi izlaznu fakturu',
    'allocation_pick_purchase_invoice': 'Odaberi ulaznu fakturu',
    'allocation_exceeds_unallocated': 'Zbir alokacija premašuje raspoloživi iznos transakcije.',
    'allocation_amount_required': 'Unesite iznos alokacije.',
    'allocation_amount_decimals': 'Najviše dvije decimale.',
    'allocation_amount_invalid': 'Iznos mora biti pozitivan.',
    'allocation_cancel': 'Poništi alokaciju',
    'allocation_cancel_confirm': 'Poništi',
    'allocation_cancel_warning':
        'Saldo računa se neće promijeniti. Faktura će ponovo dobiti otvoreni iznos. Originalna Cash Flow transakcija ostaje knjižena. Alokacija ostaje u historiji kao poništena.',
    'allocation_cancel_reason': 'Razlog poništenja',
    'allocation_cancelled': 'Alokacija je poništena.',
    'allocation_status_active': 'Aktivna',
    'allocation_status_cancelled': 'Poništena',
    'allocation_allocated_by': 'Alocirao',
    'allocation_allocated_at': 'Datum alokacije',
    'allocation_cancelled_at': 'Datum poništenja',
    'allocation_cancelled_by': 'Poništio',
    'invoice_number': 'Broj fakture',
    'card_planned_items_title': 'Planirane stavke',
    'card_planned_items_subtitle':
        'Planirani prilivi i odlivi s vjerovatnoćom i lifecycle odobrenja.',
    'card_forecast_title': 'Cash Flow prognoza',
    'card_forecast_subtitle':
        'Deterministička prognoza novčanog toka po bucketima (Callable sloj).',
    'planned_items_title': 'Planirane stavke',
    'planned_items_empty': 'Nema planiranih stavki za odabrane filtere.',
    'planned_item_new': 'Nova planirana stavka',
    'planned_item_edit': 'Uredi nacrt planirane stavke',
    'planned_item_detail': 'Detalji planirane stavke',
    'planned_status_draft': 'Nacrt',
    'planned_status_approved': 'Odobreno',
    'planned_status_cancelled': 'Otkazano',
    'expected_date': 'Očekivani datum',
    'nominal_amount': 'Nominalni iznos',
    'weighted_amount': 'Ponderisani iznos',
    'probability_percent': 'Vjerovatnoća (%)',
    'probability_source': 'Izvor vjerovatnoće',
    'prob_source_manual_confirmed': 'Ručno potvrđeno',
    'prob_source_company_rule': 'Pravilo kompanije',
    'prob_source_system_default': 'Sistemski zadano',
    'approve_planned_item': 'Odobri stavku',
    'approve_planned_item_confirm':
        'Odobrena stavka ulazi u prognozu. Nakon odobrenja izmjena kanonskih polja nije dozvoljena. Nastaviti?',
    'cancel_planned_item': 'Otkaži stavku',
    'cancel_planned_item_confirm':
        'Stavka više neće ulaziti u prognozu. Nastaviti?',
    'planned_item_approved': 'Planirana stavka je odobrena.',
    'planned_item_cancelled': 'Planirana stavka je otkazana.',
    'planned_readonly_hint':
        'Odobrena stavka je read-only. Korekcija: otkaz + nova stavka.',
    'forecast_title': 'Cash Flow prognoza',
    'forecast_horizon': 'Horizont (dana)',
    'forecast_custom_period': 'Prilagođeni period',
    'forecast_use_horizon': 'Preset horizont',
    'forecast_use_custom': 'Prilagođeni period',
    'forecast_bucket_type': 'Vrsta bucketa',
    'forecast_bucket_day': 'Dan',
    'forecast_bucket_week': 'Sedmica',
    'forecast_bucket_month': 'Mjesec',
    'forecast_opening_balance': 'Početno stanje',
    'forecast_actual_inflows': 'Stvarni prilivi',
    'forecast_actual_outflows': 'Stvarni odlivi',
    'forecast_planned_nominal_inflows': 'Planirani nominalni prilivi',
    'forecast_planned_nominal_outflows': 'Planirani nominalni odlivi',
    'forecast_planned_weighted_inflows': 'Planirani ponderisani prilivi',
    'forecast_planned_weighted_outflows': 'Planirani ponderisani odlivi',
    'forecast_nominal_closing': 'Nominalni završni saldo',
    'forecast_weighted_closing': 'Ponderisani završni saldo',
    'forecast_buckets_empty': 'Nema bucket-a za odabrane parametre.',
    'forecast_minimum_cash_reserve': 'Minimalna gotovinska rezerva',
    'forecast_first_below_reserve_nominal': 'Prvi nominalni pad ispod rezerve',
    'forecast_first_below_reserve_weighted': 'Prvi ponderisani pad ispod rezerve',
    'forecast_min_nominal_balance': 'Minimalni nominalni saldo',
    'forecast_min_nominal_balance_date': 'Datum minimalnog nominalnog salda',
    'forecast_min_weighted_balance': 'Minimalni ponderisani saldo',
    'forecast_min_weighted_balance_date': 'Datum minimalnog ponderisanog salda',
    'forecast_negative_nominal_expected': 'Očekivan negativan nominalni saldo',
    'forecast_negative_weighted_expected': 'Očekivan negativan ponderisani saldo',
    'forecast_yes': 'Da',
    'forecast_no': 'Ne',
    'forecast_load': 'Učitaj prognozu',
    'forecast_period_label': 'Period prognoze',
    'advisory_section_title': 'Proaktivni finansijski nadzor',
    'advisory_controlling_section_title': 'Kontroling AI analiza',
    'advisory_empty': 'Nema upozorenja za odabrane filtere.',
    'advisory_load_error': 'Učitavanje upozorenja nije uspjelo.',
    'advisory_alert_not_found':
        'Upozorenje više nije dostupno. Možda je riješeno ili uklonjeno iz sustava.',
    'advisory_filter_status': 'Status',
    'advisory_filter_severity': 'Ozbiljnost',
    'advisory_filter_plant': 'Pogon',
    'advisory_filter_active': 'Aktivna upozorenja',
    'advisory_filter_history': 'Historija',
    'advisory_filter_all_plants': 'Svi pogoni',
    'advisory_filter_all_severities': 'Sve razine',
    'advisory_run_analysis': 'Analiziraj sada',
    'advisory_run_analysis_running': 'Analiza u tijeku…',
    'advisory_run_summary':
        'Evaluirano pravila: {rules} · nova: {created} · ažurirana: {updated} · riješena: {resolved} · preskočeno: {skipped}',
    'advisory_confidence_label': 'Pouzdanost: {score}%',
    'advisory_confidence_score': 'Pouzdanost',
    'advisory_plant_scope': 'Pogon: {plant}',
    'advisory_detected_range': 'Prvo otkriveno: {first} · zadnje: {last}',
    'advisory_severity_info': 'Informacija',
    'advisory_severity_medium': 'Srednja',
    'advisory_severity_high': 'Visoka',
    'advisory_severity_critical': 'Kritična',
    'advisory_status_open': 'Otvoreno',
    'advisory_status_acknowledged': 'Pregledano',
    'advisory_status_resolved': 'Riješeno',
    'advisory_status_dismissed': 'Odbačeno',
    'advisory_detail_title': 'Detalj upozorenja',
    'advisory_section_observed': 'Šta je Operonix uočio?',
    'advisory_section_why': 'Zašto mi Operonix ovo prikazuje?',
    'advisory_section_assessment': 'Procjena',
    'advisory_section_recommendation': 'Preporučena naredna akcija',
    'advisory_confidence_origin': 'Izvor pouzdanosti',
    'advisory_confidence_factors': 'Faktori pouzdanosti',
    'advisory_analysis_date': 'Datum analize',
    'advisory_facts_empty': 'Nema dostupnih činjenica za ovo upozorenje.',
    'advisory_fact_as_of': 'Stanje na: {date}',
    'advisory_acknowledge': 'Potvrdi da je pregledano',
    'advisory_acknowledged': 'Upozorenje je označeno kao pregledano.',
    'advisory_dismiss': 'Odbaci upozorenje',
    'advisory_dismissed': 'Upozorenje je odbačeno.',
    'advisory_feedback': 'Pošalji feedback',
    'advisory_feedback_title': 'Feedback na upozorenje',
    'advisory_feedback_helpful': 'Tačno',
    'advisory_feedback_not_helpful': 'Djelimično tačno',
    'advisory_feedback_incorrect_facts': 'Netačno',
    'advisory_feedback_wrong_severity': 'Nije relevantno',
    'advisory_feedback_comment': 'Komentar (opcionalno)',
    'advisory_feedback_submit': 'Pošalji feedback',
    'advisory_feedback_sent': 'Feedback je zaprimljen.',
    'advisory_dismiss_title': 'Razlog odbacivanja',
    'advisory_dismiss_confirm': 'Odbaci upozorenje',
    'advisory_dismiss_other': 'Opišite razlog',
    'advisory_dismiss_reason_risk_resolved': 'Rizik je već riješen',
    'advisory_dismiss_reason_known_circumstance': 'Poznata poslovna okolnost',
    'advisory_dismiss_reason_incorrect_incomplete_data':
        'Netačni ili nepotpuni podaci',
    'advisory_dismiss_reason_not_relevant': 'Nije relevantno',
    'advisory_dismiss_reason_other': 'Drugi razlog',
    'advisory_open_recommendation': 'Otvori preporučeni ekran',
    'advisory_resolution_reason': 'Razlog rješenja',
    'advisory_dismiss_reason_label': 'Razlog odbacivanja',
    'advisory_origin_deterministic_only': 'Procjena iz poslovnih podataka',
    'advisory_origin_deterministic_with_ai_interpretation':
        'Procjena iz podataka s AI objašnjenjem',
    'advisory_origin_insufficient_facts': 'Nedovoljno podataka za pouzdanu procjenu',
    'advisory_snapshot_threshold': 'Operativni prag',
    'advisory_snapshot_minimum_cash_reserve': 'Minimalna gotovinska rezerva',
    'advisory_snapshot_base_currency': 'Osnovna valuta',
    'advisory_snapshot_first_nominal_below_reserve_date':
        'Prvi datum ispod rezerve (nominalno)',
    'advisory_snapshot_first_weighted_below_reserve_date':
        'Prvi datum ispod rezerve (ponderisano)',
    'advisory_snapshot_minimum_nominal_balance': 'Najniži nominalni saldo',
    'advisory_snapshot_minimum_weighted_balance': 'Najniži ponderisani saldo',
    'advisory_snapshot_nominal_negative_balance_expected':
        'Očekivan negativan saldo (nominalno)',
    'advisory_snapshot_weighted_negative_balance_expected':
        'Očekivan negativan saldo (ponderisano)',
    'advisory_snapshot_customer_name': 'Kupac',
    'advisory_snapshot_supplier_name': 'Dobavljač',
    'advisory_snapshot_direction': 'Smjer',
    'advisory_snapshot_allocated_amount': 'Raspodijeljeni iznos',
    'advisory_snapshot_unallocated_amount': 'Neraspodijeljeni iznos',
    'advisory_snapshot_nominal_amount': 'Nominalni iznos',
    'advisory_snapshot_status': 'Status',
    'advisory_factor_fact_completeness': 'Potpunost podataka',
    'advisory_factor_forecast_horizon_days': 'Horizont prognoze',
    'advisory_factor_signal_strength': 'Jačina signala',
    'advisory_factor_data_freshness': 'Svježina podataka',
    'advisory_factor_days_one': '1 dan',
    'advisory_factor_days_many': '{count} dana',
    'advisory_freshness_current': 'Aktualni podaci',
    'advisory_freshness_minutes': 'Prije {count} min',
    'advisory_freshness_hours': 'Prije {count} h',
    'advisory_rule_liquidity_below_minimum_reserve_nominal':
        'Likvidnost ispod minimalne rezerve (nominalno)',
    'advisory_rule_liquidity_below_minimum_reserve_weighted':
        'Likvidnost ispod minimalne rezerve (ponderisano)',
    'advisory_rule_liquidity_negative_balance_expected_nominal':
        'Očekivan negativan saldo (nominalno)',
    'advisory_rule_liquidity_negative_balance_expected_weighted':
        'Očekivan negativan saldo (ponderisano)',
    'advisory_rule_receivables_overdue_material':
        'Značajna dospjela potraživanja',
    'advisory_rule_payables_due_soon_cluster':
        'Skup obaveza uskoro dospijeva',
    'advisory_rule_cash_unallocated_surplus': 'Neraspodijeljen višak gotovine',
    'advisory_rule_planned_items_draft_backlog':
        'Zaostali nacrti planiranih stavki',
    'advisory_rule_accounts_low_balance_single': 'Nizak saldo računa',
    'advisory_fact_forecast_liquidity_threshold': 'Prag likvidnosti iz prognoze',
    'advisory_fact_sales_invoice_open': 'Otvorena izlazna faktura',
    'advisory_fact_purchase_invoice_open': 'Otvorena ulazna faktura',
    'advisory_fact_cash_transaction': 'Gotovinska transakcija',
    'advisory_fact_planned_cash_item': 'Planirana stavka',
    'advisory_fact_account_balance': 'Saldo računa',
    'notification_section_title': 'In-app obavijesti',
    'notification_empty': 'Nema obavijesti za odabrane filtere.',
    'notification_load_error': 'Učitavanje obavijesti nije uspjelo.',
    'notification_filter_active': 'Aktivne',
    'notification_filter_history': 'Historija',
    'notification_filter_all': 'Sve',
    'notification_filter_unread': 'Nepročitane',
    'notification_scope_company_wide': 'Cijela kompanija',
    'notification_plant_scope': 'Pogon: {plant}',
    'notification_scope_label': 'Opseg',
    'notification_delivered_at': 'Dostavljeno: {time}',
    'notification_generation_revision': 'Generacija {gen} · revizija {rev}',
    'notification_detail_title': 'Detalj obavijesti',
    'notification_delivery_status': 'Status dostave',
    'notification_mark_read': 'Označi kao pročitano',
    'notification_marked_read': 'Obavijest je označena kao pročitana.',
    'notification_open_alert': 'Otvori povezano upozorenje',
    'notification_alert_unavailable':
        'Povezano upozorenje više nije u sustavu. Prikazani su podaci iz obavijesti.',
    'notification_closed_reason': 'Razlog zatvaranja',
    'notification_status_unread': 'Nepročitano',
    'notification_status_read': 'Pročitano',
    'notification_status_acknowledged': 'Potvrđeno',
    'notification_status_superseded': 'Zamijenjeno',
    'notification_status_closed': 'Zatvoreno',
  };

  static const _en = <String, String>{
    'finance_hub_title': 'Finance',
    'finance_hub_subtitle':
        'Operational cash flow — accounts, categories and transactions (Callable layer).',
    'card_accounts_title': 'Accounts',
    'card_accounts_subtitle':
        'Bank accounts, cash registers and current cash balance.',
    'card_categories_title': 'Cash Flow categories',
    'card_categories_subtitle':
        'Category catalog for operating, investing and financing flows.',
    'module_not_enabled':
        'The finance_controlling module is not enabled for this company.',
    'access_denied': 'You do not have access to the Finance module.',
    'accounts_title': 'Accounts and cash registers',
    'accounts_empty': 'No accounts recorded.',
    'account_new': 'New account',
    'account_edit': 'Edit account',
    'account_code': 'Account code',
    'account_name': 'Name',
    'account_type': 'Account type',
    'currency': 'Currency',
    'opening_balance': 'Opening balance',
    'current_balance': 'Current balance',
    'bank_name': 'Bank',
    'iban': 'IBAN',
    'plant_key': 'Plant',
    'active': 'Active',
    'inactive': 'Inactive',
    'deactivate_account': 'Deactivate account',
    'deactivate_account_confirm':
        'The account will no longer be available for new transactions. Continue?',
    'save': 'Save',
    'cancel': 'Cancel',
    'refresh': 'Refresh',
    'categories_title': 'Cash Flow categories',
    'categories_empty': 'No categories.',
    'category_new': 'New category',
    'category_edit': 'Edit category',
    'category_code': 'Category code',
    'category_name': 'Category name',
    'activity_type': 'Activity type',
    'activity_operating': 'Operating activity',
    'activity_investing': 'Investing activity',
    'activity_financing': 'Financing activity',
    'sort_order': 'Sort order',
    'deactivate_category': 'Deactivate category',
    'deactivate_category_confirm':
        'The category will no longer be available for new entries. Continue?',
    'filter_active_only': 'Active only',
    'type_transactional': 'Transactional account',
    'type_foreign_currency': 'Foreign currency account',
    'type_cash_register': 'Cash register',
    'type_virtual': 'Virtual account',
    'type_credit_line': 'Credit line',
    'error_generic': 'Something went wrong. Please try again.',
    'saved': 'Saved.',
    'deactivated': 'Deactivated.',
    'pick_date': 'Pick date',
    'card_transactions_title': 'Transactions',
    'card_transactions_subtitle':
        'Drafts, posting, reconciliation and reversal of operational cash flows.',
    'card_realized_title': 'Realized Cash Flow',
    'card_realized_subtitle':
        'Summary of posted and reconciled transactions for the selected period.',
    'transactions_title': 'Transactions',
    'transactions_empty': 'No transactions for the selected filters.',
    'transaction_new': 'New transaction',
    'transaction_edit': 'Edit draft',
    'transaction_detail': 'Transaction details',
    'transaction_code': 'Transaction code',
    'transaction_date': 'Transaction date',
    'value_date': 'Value date',
    'amount': 'Amount',
    'direction': 'Direction',
    'direction_inflow': 'Inflow',
    'direction_outflow': 'Outflow',
    'status': 'Status',
    'tx_status_draft': 'Draft',
    'tx_status_planned': 'Planned',
    'tx_status_posted': 'Posted',
    'tx_status_reconciled': 'Reconciled',
    'tx_status_cancelled': 'Cancelled',
    'description': 'Description',
    'reference': 'Reference',
    'filter_status': 'Status',
    'filter_account': 'Account',
    'filter_direction': 'Direction',
    'filter_period': 'Period',
    'filter_all': 'All',
    'filter_all_accounts': 'All accounts',
    'date_from': 'Date from',
    'date_to': 'Date to',
    'account': 'Account',
    'category': 'Category',
    'post_transaction': 'Post',
    'post_transaction_confirm':
        'Posting changes the account balance. Continue?',
    'reconcile_transaction': 'Reconcile',
    'reconcile_transaction_confirm':
        'Reconciliation does not change the account balance. Continue?',
    'reverse_transaction': 'Reverse',
    'reverse_transaction_confirm':
        'Reversal creates a new transaction in the opposite direction. The original remains in history. Continue?',
    'cancel_draft': 'Cancel draft',
    'cancel_draft_confirm':
        'The draft will be cancelled without changing the balance. Continue?',
    'posted': 'Posted.',
    'reconciled': 'Reconciled.',
    'reversed': 'Reversal completed.',
    'draft_cancelled': 'Draft cancelled.',
    'audit_section': 'Audit trail',
    'audit_created_by': 'Created by',
    'audit_posted_by': 'Posted by',
    'audit_reconciled_by': 'Reconciled by',
    'audit_posted_at': 'Posted at',
    'audit_reconciled_at': 'Reconciled at',
    'link_reversal': 'Reversal transaction',
    'link_original': 'Original transaction',
    'realized_title': 'Realized Cash Flow',
    'realized_period': 'Period',
    'realized_total_inflows': 'Total inflows',
    'realized_total_outflows': 'Total outflows',
    'realized_net_cash_flow': 'Net cash flow',
    'realized_closing_balance': 'Closing balance',
    'realized_transaction_count': 'Transaction count',
    'realized_by_activity': 'By activity type',
    'realized_inflows': 'Inflows',
    'realized_outflows': 'Outflows',
    'realized_net': 'Net',
    'load_report': 'Load report',
    'select_account': 'Select account',
    'select_category': 'Select category',
    'select_direction': 'Select direction',
    'invoices_hub_subtitle':
        'Invoices, receivables and payables — Callable layer (P2).',
    'card_sales_invoices_title': 'Sales invoices',
    'card_sales_invoices_subtitle':
        'Drafts, issue and receivables per invoice.',
    'card_purchase_invoices_title': 'Purchase invoices',
    'card_purchase_invoices_subtitle':
        'Drafts, approval and payables per invoice.',
    'card_receivables_title': 'Receivables',
    'card_receivables_subtitle':
        'Open and partially paid sales invoices.',
    'card_payables_title': 'Payables',
    'card_payables_subtitle':
        'Open and partially paid purchase invoices.',
    'sales_invoices_title': 'Sales invoices',
    'sales_invoices_empty': 'No sales invoices.',
    'sales_invoice_new': 'New sales invoice',
    'sales_invoice_edit': 'Edit sales invoice draft',
    'purchase_invoices_title': 'Purchase invoices',
    'purchase_invoices_empty': 'No purchase invoices.',
    'purchase_invoice_new': 'New purchase invoice',
    'purchase_invoice_edit': 'Edit purchase invoice draft',
    'receivables_title': 'Receivables',
    'receivables_empty': 'No open receivables.',
    'receivables_open_list': 'Open and partially paid invoices',
    'payables_title': 'Payables',
    'payables_empty': 'No open payables.',
    'payables_open_list': 'Open and partially paid obligations',
    'customer_id': 'Customer code',
    'customer_name': 'Customer',
    'supplier_id': 'Supplier code',
    'supplier_name': 'Supplier',
    'net_amount': 'Net amount',
    'tax_amount': 'Tax amount',
    'total_amount': 'Total amount',
    'paid_amount': 'Paid',
    'open_amount': 'Open',
    'issue_date': 'Issue date',
    'due_date': 'Due date',
    'issue_sales_invoice': 'Issue invoice',
    'approve_purchase_invoice': 'Approve invoice',
    'cancel_invoice': 'Cancel invoice',
    'cancel_invoice_confirm':
        'The invoice will be cancelled per backend lifecycle rules. Continue?',
    'invoice_issued': 'Invoice issued.',
    'invoice_approved': 'Invoice approved.',
    'invoice_cancelled': 'Invoice cancelled.',
    'invoice_overdue': 'Overdue',
    'invoice_erp_synced': 'ERP',
    'invoice_erp_readonly_hint':
        'ERP-synced invoice: ERP-owned fields are not editable.',
    'open_items_count': 'Open invoice count',
    'open_items_total': 'Total open amount',
    'open_items_overdue_count': 'Overdue invoice count',
    'open_items_overdue_amount': 'Overdue amount',
    'inv_status_draft': 'Draft',
    'inv_status_open': 'Open',
    'inv_status_partial': 'Partially paid',
    'inv_status_paid': 'Paid',
    'inv_status_cancelled': 'Cancelled',
    'allocate_to_invoices': 'Allocate to invoices',
    'allocated_amount': 'Allocated',
    'unallocated_amount': 'Unallocated',
    'payment_allocations_section': 'Payment allocations',
    'allocations_empty': 'No allocations.',
    'allocations_active_total': 'Total actively allocated',
    'allocation_add_invoice': 'Add invoice',
    'allocation_lines_empty': 'Add one or more invoices to allocate.',
    'allocation_line_amount': 'Allocation amount',
    'allocation_invoice_remaining': 'Remaining open invoice amount',
    'allocation_batch_total': 'Allocation batch total',
    'allocation_remaining_tx': 'Remaining unallocated transaction amount',
    'allocation_confirm': 'Confirm allocation',
    'allocation_saved': 'Allocation saved.',
    'allocation_no_invoices': 'No matching open invoices.',
    'allocation_pick_sales_invoice': 'Select sales invoice',
    'allocation_pick_purchase_invoice': 'Select purchase invoice',
    'allocation_exceeds_unallocated':
        'Allocation total exceeds available unallocated amount.',
    'allocation_amount_required': 'Enter an allocation amount.',
    'allocation_amount_decimals': 'At most two decimal places.',
    'allocation_amount_invalid': 'Amount must be positive.',
    'allocation_cancel': 'Cancel allocation',
    'allocation_cancel_confirm': 'Cancel',
    'allocation_cancel_warning':
        'The account balance will not change. The invoice will regain its open amount. The original Cash Flow transaction remains posted. The allocation stays in history as cancelled.',
    'allocation_cancel_reason': 'Cancellation reason',
    'allocation_cancelled': 'Allocation cancelled.',
    'allocation_status_active': 'Active',
    'allocation_status_cancelled': 'Cancelled',
    'allocation_allocated_by': 'Allocated by',
    'allocation_allocated_at': 'Allocation date',
    'allocation_cancelled_at': 'Cancelled at',
    'allocation_cancelled_by': 'Cancelled by',
    'invoice_number': 'Invoice number',
    'card_planned_items_title': 'Planned items',
    'card_planned_items_subtitle':
        'Planned inflows and outflows with probability and approval lifecycle.',
    'card_forecast_title': 'Cash Flow forecast',
    'card_forecast_subtitle':
        'Deterministic cash flow forecast by buckets (Callable layer).',
    'planned_items_title': 'Planned items',
    'planned_items_empty': 'No planned items for the selected filters.',
    'planned_item_new': 'New planned item',
    'planned_item_edit': 'Edit planned item draft',
    'planned_item_detail': 'Planned item details',
    'planned_status_draft': 'Draft',
    'planned_status_approved': 'Approved',
    'planned_status_cancelled': 'Cancelled',
    'expected_date': 'Expected date',
    'nominal_amount': 'Nominal amount',
    'weighted_amount': 'Weighted amount',
    'probability_percent': 'Probability (%)',
    'probability_source': 'Probability source',
    'prob_source_manual_confirmed': 'Manually confirmed',
    'prob_source_company_rule': 'Company rule',
    'prob_source_system_default': 'System default',
    'approve_planned_item': 'Approve item',
    'approve_planned_item_confirm':
        'Approved items enter the forecast. Canonical fields cannot be edited after approval. Continue?',
    'cancel_planned_item': 'Cancel item',
    'cancel_planned_item_confirm':
        'The item will no longer appear in the forecast. Continue?',
    'planned_item_approved': 'Planned item approved.',
    'planned_item_cancelled': 'Planned item cancelled.',
    'planned_readonly_hint':
        'Approved items are read-only. Correction: cancel + new item.',
    'forecast_title': 'Cash Flow forecast',
    'forecast_horizon': 'Horizon (days)',
    'forecast_custom_period': 'Custom period',
    'forecast_use_horizon': 'Preset horizon',
    'forecast_use_custom': 'Custom period',
    'forecast_bucket_type': 'Bucket type',
    'forecast_bucket_day': 'Day',
    'forecast_bucket_week': 'Week',
    'forecast_bucket_month': 'Month',
    'forecast_opening_balance': 'Opening balance',
    'forecast_actual_inflows': 'Actual inflows',
    'forecast_actual_outflows': 'Actual outflows',
    'forecast_planned_nominal_inflows': 'Planned nominal inflows',
    'forecast_planned_nominal_outflows': 'Planned nominal outflows',
    'forecast_planned_weighted_inflows': 'Planned weighted inflows',
    'forecast_planned_weighted_outflows': 'Planned weighted outflows',
    'forecast_nominal_closing': 'Nominal closing balance',
    'forecast_weighted_closing': 'Weighted closing balance',
    'forecast_buckets_empty': 'No buckets for the selected parameters.',
    'forecast_minimum_cash_reserve': 'Minimum cash reserve',
    'forecast_first_below_reserve_nominal': 'First nominal below reserve',
    'forecast_first_below_reserve_weighted': 'First weighted below reserve',
    'forecast_min_nominal_balance': 'Minimum nominal balance',
    'forecast_min_nominal_balance_date': 'Minimum nominal balance date',
    'forecast_min_weighted_balance': 'Minimum weighted balance',
    'forecast_min_weighted_balance_date': 'Minimum weighted balance date',
    'forecast_negative_nominal_expected': 'Negative nominal balance expected',
    'forecast_negative_weighted_expected': 'Negative weighted balance expected',
    'forecast_yes': 'Yes',
    'forecast_no': 'No',
    'forecast_load': 'Load forecast',
    'forecast_period_label': 'Forecast period',
    'advisory_section_title': 'Proactive financial monitoring',
    'advisory_controlling_section_title': 'Controlling AI analysis',
    'advisory_empty': 'No alerts for the selected filters.',
    'advisory_load_error': 'Failed to load alerts.',
    'advisory_alert_not_found':
        'This alert is no longer available. It may have been resolved or removed.',
    'advisory_filter_status': 'Status',
    'advisory_filter_severity': 'Severity',
    'advisory_filter_plant': 'Plant',
    'advisory_filter_active': 'Active alerts',
    'advisory_filter_history': 'History',
    'advisory_filter_all_plants': 'All plants',
    'advisory_filter_all_severities': 'All levels',
    'advisory_run_analysis': 'Analyze now',
    'advisory_run_analysis_running': 'Analysis in progress…',
    'advisory_run_summary':
        'Rules evaluated: {rules} · new: {created} · updated: {updated} · resolved: {resolved} · skipped: {skipped}',
    'advisory_confidence_label': 'Confidence: {score}%',
    'advisory_confidence_score': 'Confidence',
    'advisory_plant_scope': 'Plant: {plant}',
    'advisory_detected_range': 'First detected: {first} · last: {last}',
    'advisory_severity_info': 'Info',
    'advisory_severity_medium': 'Medium',
    'advisory_severity_high': 'High',
    'advisory_severity_critical': 'Critical',
    'advisory_status_open': 'Open',
    'advisory_status_acknowledged': 'Acknowledged',
    'advisory_status_resolved': 'Resolved',
    'advisory_status_dismissed': 'Dismissed',
    'advisory_detail_title': 'Alert detail',
    'advisory_section_observed': 'What did Operonix notice?',
    'advisory_section_why': 'Why is Operonix showing this?',
    'advisory_section_assessment': 'Assessment',
    'advisory_section_recommendation': 'Recommended next action',
    'advisory_confidence_origin': 'Confidence origin',
    'advisory_confidence_factors': 'Confidence factors',
    'advisory_analysis_date': 'Analysis date',
    'advisory_facts_empty': 'No facts available for this alert.',
    'advisory_fact_as_of': 'As of: {date}',
    'advisory_acknowledge': 'Mark as reviewed',
    'advisory_acknowledged': 'Alert marked as reviewed.',
    'advisory_dismiss': 'Dismiss alert',
    'advisory_dismissed': 'Alert dismissed.',
    'advisory_feedback': 'Send feedback',
    'advisory_feedback_title': 'Alert feedback',
    'advisory_feedback_helpful': 'Accurate',
    'advisory_feedback_not_helpful': 'Partially accurate',
    'advisory_feedback_incorrect_facts': 'Incorrect',
    'advisory_feedback_wrong_severity': 'Not relevant',
    'advisory_feedback_comment': 'Comment (optional)',
    'advisory_feedback_submit': 'Submit feedback',
    'advisory_feedback_sent': 'Feedback received.',
    'advisory_dismiss_title': 'Dismiss reason',
    'advisory_dismiss_confirm': 'Dismiss alert',
    'advisory_dismiss_other': 'Describe the reason',
    'advisory_dismiss_reason_risk_resolved': 'Risk already resolved',
    'advisory_dismiss_reason_known_circumstance': 'Known business circumstance',
    'advisory_dismiss_reason_incorrect_incomplete_data':
        'Incorrect or incomplete data',
    'advisory_dismiss_reason_not_relevant': 'Not relevant',
    'advisory_dismiss_reason_other': 'Other reason',
    'advisory_open_recommendation': 'Open recommended screen',
    'advisory_resolution_reason': 'Resolution reason',
    'advisory_dismiss_reason_label': 'Dismiss reason',
    'advisory_origin_deterministic_only': 'Assessment from business data',
    'advisory_origin_deterministic_with_ai_interpretation':
        'Assessment from data with AI explanation',
    'advisory_origin_insufficient_facts':
        'Insufficient data for a reliable assessment',
    'advisory_snapshot_threshold': 'Operating threshold',
    'advisory_snapshot_minimum_cash_reserve': 'Minimum cash reserve',
    'advisory_snapshot_base_currency': 'Base currency',
    'advisory_snapshot_first_nominal_below_reserve_date':
        'First date below reserve (nominal)',
    'advisory_snapshot_first_weighted_below_reserve_date':
        'First date below reserve (weighted)',
    'advisory_snapshot_minimum_nominal_balance': 'Lowest nominal balance',
    'advisory_snapshot_minimum_weighted_balance': 'Lowest weighted balance',
    'advisory_snapshot_nominal_negative_balance_expected':
        'Negative balance expected (nominal)',
    'advisory_snapshot_weighted_negative_balance_expected':
        'Negative balance expected (weighted)',
    'advisory_snapshot_customer_name': 'Customer',
    'advisory_snapshot_supplier_name': 'Supplier',
    'advisory_snapshot_direction': 'Direction',
    'advisory_snapshot_allocated_amount': 'Allocated amount',
    'advisory_snapshot_unallocated_amount': 'Unallocated amount',
    'advisory_snapshot_nominal_amount': 'Nominal amount',
    'advisory_snapshot_status': 'Status',
    'advisory_factor_fact_completeness': 'Data completeness',
    'advisory_factor_forecast_horizon_days': 'Forecast horizon',
    'advisory_factor_signal_strength': 'Signal strength',
    'advisory_factor_data_freshness': 'Data freshness',
    'advisory_factor_days_one': '1 day',
    'advisory_factor_days_many': '{count} days',
    'advisory_freshness_current': 'Current data',
    'advisory_freshness_minutes': '{count} min ago',
    'advisory_freshness_hours': '{count} h ago',
    'advisory_rule_liquidity_below_minimum_reserve_nominal':
        'Liquidity below minimum reserve (nominal)',
    'advisory_rule_liquidity_below_minimum_reserve_weighted':
        'Liquidity below minimum reserve (weighted)',
    'advisory_rule_liquidity_negative_balance_expected_nominal':
        'Negative balance expected (nominal)',
    'advisory_rule_liquidity_negative_balance_expected_weighted':
        'Negative balance expected (weighted)',
    'advisory_rule_receivables_overdue_material':
        'Material overdue receivables',
    'advisory_rule_payables_due_soon_cluster': 'Payables due soon cluster',
    'advisory_rule_cash_unallocated_surplus': 'Unallocated cash surplus',
    'advisory_rule_planned_items_draft_backlog': 'Draft planned items backlog',
    'advisory_rule_accounts_low_balance_single': 'Low single account balance',
    'advisory_fact_forecast_liquidity_threshold':
        'Liquidity threshold from forecast',
    'advisory_fact_sales_invoice_open': 'Open sales invoice',
    'advisory_fact_purchase_invoice_open': 'Open purchase invoice',
    'advisory_fact_cash_transaction': 'Cash transaction',
    'advisory_fact_planned_cash_item': 'Planned cash item',
    'advisory_fact_account_balance': 'Account balance',
    'notification_section_title': 'In-app notifications',
    'notification_empty': 'No notifications for the selected filters.',
    'notification_load_error': 'Failed to load notifications.',
    'notification_filter_active': 'Active',
    'notification_filter_history': 'History',
    'notification_filter_all': 'All',
    'notification_filter_unread': 'Unread',
    'notification_scope_company_wide': 'Entire company',
    'notification_plant_scope': 'Plant: {plant}',
    'notification_scope_label': 'Scope',
    'notification_delivered_at': 'Delivered: {time}',
    'notification_generation_revision': 'Generation {gen} · revision {rev}',
    'notification_detail_title': 'Notification detail',
    'notification_delivery_status': 'Delivery status',
    'notification_mark_read': 'Mark as read',
    'notification_marked_read': 'Notification marked as read.',
    'notification_open_alert': 'Open linked alert',
    'notification_alert_unavailable':
        'The linked alert is no longer in the system. Notification details are shown below.',
    'notification_closed_reason': 'Close reason',
    'notification_status_unread': 'Unread',
    'notification_status_read': 'Read',
    'notification_status_acknowledged': 'Acknowledged',
    'notification_status_superseded': 'Superseded',
    'notification_status_closed': 'Closed',
  };
}
