import 'package:flutter/widgets.dart';

/// Finance modul — BA (default) i EN stringovi (bez generičkog skraćivanja naziva modula).
class FinanceStrings {
  FinanceStrings._();

  static bool isEnglish(BuildContext context) {
    return Localizations.localeOf(context).languageCode == 'en';
  }

  static String t(BuildContext context, String key) {
    final en = isEnglish(context);
    final map = en ? _en : _bs;
    return map[key] ?? key;
  }

  static const _bs = <String, String>{
    'finance_hub_title': 'Finance',
    'finance_hub_subtitle':
        'Operativni novčani tok — računi, kategorije i transakcije (Callable sloj).',
    'card_accounts_title': 'Računi',
    'card_accounts_subtitle':
        'Bankovni računi, blagajne i trenutno stanje novca.',
    'card_categories_title': 'Cash Flow kategorije',
    'card_categories_subtitle':
        'Šifrarnik kategorija za operativne, investicione i finansijske tokove.',
    'module_not_enabled':
        'Modul finance_controlling nije uključen za ovu kompaniju.',
    'access_denied': 'Nemate pravo pristupa Finance modulu.',
    'accounts_title': 'Računi i blagajne',
    'accounts_empty': 'Nema evidentiranih računa.',
    'account_new': 'Novi račun',
    'account_edit': 'Uredi račun',
    'account_code': 'Šifra računa',
    'account_name': 'Naziv',
    'account_type': 'Vrsta računa',
    'currency': 'Valuta',
    'opening_balance': 'Početno stanje',
    'current_balance': 'Trenutno stanje',
    'bank_name': 'Banka',
    'iban': 'IBAN',
    'plant_key': 'Pogon',
    'active': 'Aktivan',
    'inactive': 'Neaktivan',
    'deactivate_account': 'Deaktiviraj račun',
    'deactivate_account_confirm':
        'Račun više neće biti dostupan za nove transakcije. Nastaviti?',
    'save': 'Spremi',
    'cancel': 'Odustani',
    'refresh': 'Osvježi',
    'categories_title': 'Cash Flow kategorije',
    'categories_empty': 'Nema kategorija.',
    'category_new': 'Nova kategorija',
    'category_edit': 'Uredi kategoriju',
    'category_code': 'Šifra kategorije',
    'category_name': 'Naziv kategorije',
    'activity_type': 'Vrsta aktivnosti',
    'activity_operating': 'Operativna aktivnost',
    'activity_investing': 'Investiciona aktivnost',
    'activity_financing': 'Finansijska aktivnost',
    'sort_order': 'Redoslijed',
    'deactivate_category': 'Deaktiviraj kategoriju',
    'deactivate_category_confirm': 'Kategorija više neće biti dostupna za nove unose. Nastaviti?',
    'filter_active_only': 'Samo aktivne',
    'type_transactional': 'Transakcijski račun',
    'type_foreign_currency': 'Devizni račun',
    'type_cash_register': 'Blagajna',
    'type_virtual': 'Virtualni račun',
    'type_credit_line': 'Kreditni račun',
    'error_generic': 'Došlo je do greške. Pokušajte ponovo.',
    'saved': 'Spremljeno.',
    'deactivated': 'Deaktivirano.',
    'pick_date': 'Odaberi datum',
    'card_transactions_title': 'Transakcije',
    'card_transactions_subtitle':
        'Nacrti, knjiženje, usklađivanje i storno operativnih novčanih tokova.',
    'card_realized_title': 'Realizovani Cash Flow',
    'card_realized_subtitle':
        'Sažetak knjiženih i usklađenih transakcija za odabrani period.',
    'transactions_title': 'Transakcije',
    'transactions_empty': 'Nema transakcija za odabrane filtere.',
    'transaction_new': 'Nova transakcija',
    'transaction_edit': 'Uredi nacrt',
    'transaction_detail': 'Detalji transakcije',
    'transaction_code': 'Šifra transakcije',
    'transaction_date': 'Datum transakcije',
    'value_date': 'Datum valute',
    'amount': 'Iznos',
    'direction': 'Smjer',
    'direction_inflow': 'Priliv',
    'direction_outflow': 'Odliv',
    'status': 'Status',
    'tx_status_draft': 'Nacrt',
    'tx_status_planned': 'Planirano',
    'tx_status_posted': 'Knjiženo',
    'tx_status_reconciled': 'Usklađeno',
    'tx_status_cancelled': 'Otkazano',
    'description': 'Opis',
    'reference': 'Referenca',
    'filter_status': 'Status',
    'filter_account': 'Račun',
    'filter_direction': 'Smjer',
    'filter_period': 'Period',
    'filter_all': 'Svi',
    'filter_all_accounts': 'Svi računi',
    'date_from': 'Datum od',
    'date_to': 'Datum do',
    'account': 'Račun',
    'category': 'Kategorija',
    'post_transaction': 'Knjiži',
    'post_transaction_confirm':
        'Knjiženje mijenja saldo računa. Nastaviti?',
    'reconcile_transaction': 'Uskladi',
    'reconcile_transaction_confirm':
        'Usklađivanje ne mijenja saldo računa. Nastaviti?',
    'reverse_transaction': 'Storniraj',
    'reverse_transaction_confirm':
        'Storno kreira novu transakciju suprotnog smjera. Original ostaje u historiji. Nastaviti?',
    'cancel_draft': 'Otkaži nacrt',
    'cancel_draft_confirm': 'Nacrt će biti otkazan bez promjene salda. Nastaviti?',
    'posted': 'Knjiženo.',
    'reconciled': 'Usklađeno.',
    'reversed': 'Storno izvršen.',
    'draft_cancelled': 'Nacrt otkazan.',
    'audit_section': 'Revizija',
    'audit_created_by': 'Kreirao',
    'audit_posted_by': 'Knjižio',
    'audit_reconciled_by': 'Uskladio',
    'audit_posted_at': 'Knjiženo',
    'audit_reconciled_at': 'Usklađeno',
    'link_reversal': 'Storno transakcija',
    'link_original': 'Originalna transakcija',
    'realized_title': 'Realizovani Cash Flow',
    'realized_period': 'Period',
    'realized_total_inflows': 'Ukupni prilivi',
    'realized_total_outflows': 'Ukupni odlivi',
    'realized_net_cash_flow': 'Neto novčani tok',
    'realized_closing_balance': 'Završno stanje',
    'realized_transaction_count': 'Broj transakcija',
    'realized_by_activity': 'Po vrsti aktivnosti',
    'realized_inflows': 'Prilivi',
    'realized_outflows': 'Odlivi',
    'realized_net': 'Neto',
    'load_report': 'Učitaj izvještaj',
    'select_account': 'Odaberi račun',
    'select_category': 'Odaberi kategoriju',
    'select_direction': 'Odaberi smjer',
    'invoices_hub_subtitle':
        'Fakture, potraživanja i obaveze — Callable sloj (P2).',
    'card_sales_invoices_title': 'Izlazne fakture',
    'card_sales_invoices_subtitle':
        'Nacrti, izdavanje i pregled potraživanja po fakturi.',
    'card_purchase_invoices_title': 'Ulazne fakture',
    'card_purchase_invoices_subtitle':
        'Nacrti, odobravanje i pregled obaveza po fakturi.',
    'card_receivables_title': 'Potraživanja',
    'card_receivables_subtitle':
        'Otvorene i djelimično plaćene izlazne fakture.',
    'card_payables_title': 'Obaveze',
    'card_payables_subtitle':
        'Otvorene i djelimično plaćene ulazne fakture.',
    'sales_invoices_title': 'Izlazne fakture',
    'sales_invoices_empty': 'Nema izlaznih faktura.',
    'sales_invoice_new': 'Nova izlazna faktura',
    'sales_invoice_edit': 'Uredi nacrt izlazne fakture',
    'purchase_invoices_title': 'Ulazne fakture',
    'purchase_invoices_empty': 'Nema ulaznih faktura.',
    'purchase_invoice_new': 'Nova ulazna faktura',
    'purchase_invoice_edit': 'Uredi nacrt ulazne fakture',
    'receivables_title': 'Potraživanja',
    'receivables_empty': 'Nema otvorenih potraživanja.',
    'receivables_open_list': 'Otvorene i djelimično plaćene fakture',
    'payables_title': 'Obaveze',
    'payables_empty': 'Nema otvorenih obaveza.',
    'payables_open_list': 'Otvorene i djelimično plaćene obaveze',
    'customer_id': 'Šifra kupca',
    'customer_name': 'Kupac',
    'supplier_id': 'Šifra dobavljača',
    'supplier_name': 'Dobavljač',
    'net_amount': 'Neto iznos',
    'tax_amount': 'PDV iznos',
    'total_amount': 'Ukupan iznos',
    'paid_amount': 'Plaćeno',
    'open_amount': 'Otvoreno',
    'issue_date': 'Datum izdavanja',
    'due_date': 'Datum dospijeća',
    'issue_sales_invoice': 'Izdaj fakturu',
    'approve_purchase_invoice': 'Odobri fakturu',
    'cancel_invoice': 'Otkaži fakturu',
    'cancel_invoice_confirm':
        'Faktura će biti otkazana prema pravilima backend lifecycle-a. Nastaviti?',
    'invoice_issued': 'Faktura je izdana.',
    'invoice_approved': 'Faktura je odobrena.',
    'invoice_cancelled': 'Faktura je otkazana.',
    'invoice_overdue': 'Dospjelo',
    'invoice_erp_synced': 'ERP',
    'invoice_erp_readonly_hint':
        'ERP-sinhronizovana faktura: ERP polja nisu ručno promjenjiva.',
    'open_items_count': 'Broj otvorenih faktura',
    'open_items_total': 'Ukupan otvoreni iznos',
    'open_items_overdue_count': 'Broj dospjelih faktura',
    'open_items_overdue_amount': 'Dospjeli iznos',
    'inv_status_draft': 'Nacrt',
    'inv_status_open': 'Otvoreno',
    'inv_status_partial': 'Djelimično plaćeno',
    'inv_status_paid': 'Plaćeno',
    'inv_status_cancelled': 'Otkazano',
    'allocate_to_invoices': 'Alociraj na fakture',
    'allocated_amount': 'Alocirano',
    'unallocated_amount': 'Nealocirano',
    'payment_allocations_section': 'Alokacije plaćanja',
    'allocations_empty': 'Nema alokacija.',
    'allocations_active_total': 'Ukupno aktivno alocirano',
    'allocation_add_invoice': 'Dodaj fakturu',
    'allocation_lines_empty': 'Dodajte jednu ili više faktura za alokaciju.',
    'allocation_line_amount': 'Iznos alokacije',
    'allocation_invoice_remaining': 'Preostali otvoreni iznos fakture',
    'allocation_batch_total': 'Zbir alokacija',
    'allocation_remaining_tx': 'Preostali nealocirani iznos transakcije',
    'allocation_confirm': 'Potvrdi alokaciju',
    'allocation_saved': 'Alokacija je spremljena.',
    'allocation_no_invoices': 'Nema odgovarajućih otvorenih faktura.',
    'allocation_pick_sales_invoice': 'Odaberi izlaznu fakturu',
    'allocation_pick_purchase_invoice': 'Odaberi ulaznu fakturu',
    'allocation_exceeds_unallocated': 'Zbir alokacija premašuje raspoloživi iznos transakcije.',
    'allocation_amount_required': 'Unesite iznos alokacije.',
    'allocation_amount_decimals': 'Najviše dvije decimale.',
    'allocation_amount_invalid': 'Iznos mora biti pozitivan.',
    'allocation_cancel': 'Poništi alokaciju',
    'allocation_cancel_confirm': 'Poništi',
    'allocation_cancel_warning':
        'Saldo računa se neće promijeniti. Faktura će ponovo dobiti otvoreni iznos. Originalna Cash Flow transakcija ostaje knjižena. Alokacija ostaje u historiji kao poništena.',
    'allocation_cancel_reason': 'Razlog poništenja',
    'allocation_cancelled': 'Alokacija je poništena.',
    'allocation_status_active': 'Aktivna',
    'allocation_status_cancelled': 'Poništena',
    'allocation_allocated_by': 'Alocirao',
    'allocation_allocated_at': 'Datum alokacije',
    'allocation_cancelled_at': 'Datum poništenja',
    'allocation_cancelled_by': 'Poništio',
    'invoice_number': 'Broj fakture',
  };

  static const _en = <String, String>{
    'finance_hub_title': 'Finance',
    'finance_hub_subtitle':
        'Operational cash flow — accounts, categories and transactions (Callable layer).',
    'card_accounts_title': 'Accounts',
    'card_accounts_subtitle':
        'Bank accounts, cash registers and current cash balance.',
    'card_categories_title': 'Cash Flow categories',
    'card_categories_subtitle':
        'Category catalog for operating, investing and financing flows.',
    'module_not_enabled':
        'The finance_controlling module is not enabled for this company.',
    'access_denied': 'You do not have access to the Finance module.',
    'accounts_title': 'Accounts and cash registers',
    'accounts_empty': 'No accounts recorded.',
    'account_new': 'New account',
    'account_edit': 'Edit account',
    'account_code': 'Account code',
    'account_name': 'Name',
    'account_type': 'Account type',
    'currency': 'Currency',
    'opening_balance': 'Opening balance',
    'current_balance': 'Current balance',
    'bank_name': 'Bank',
    'iban': 'IBAN',
    'plant_key': 'Plant',
    'active': 'Active',
    'inactive': 'Inactive',
    'deactivate_account': 'Deactivate account',
    'deactivate_account_confirm':
        'The account will no longer be available for new transactions. Continue?',
    'save': 'Save',
    'cancel': 'Cancel',
    'refresh': 'Refresh',
    'categories_title': 'Cash Flow categories',
    'categories_empty': 'No categories.',
    'category_new': 'New category',
    'category_edit': 'Edit category',
    'category_code': 'Category code',
    'category_name': 'Category name',
    'activity_type': 'Activity type',
    'activity_operating': 'Operating activity',
    'activity_investing': 'Investing activity',
    'activity_financing': 'Financing activity',
    'sort_order': 'Sort order',
    'deactivate_category': 'Deactivate category',
    'deactivate_category_confirm':
        'The category will no longer be available for new entries. Continue?',
    'filter_active_only': 'Active only',
    'type_transactional': 'Transactional account',
    'type_foreign_currency': 'Foreign currency account',
    'type_cash_register': 'Cash register',
    'type_virtual': 'Virtual account',
    'type_credit_line': 'Credit line',
    'error_generic': 'Something went wrong. Please try again.',
    'saved': 'Saved.',
    'deactivated': 'Deactivated.',
    'pick_date': 'Pick date',
    'card_transactions_title': 'Transactions',
    'card_transactions_subtitle':
        'Drafts, posting, reconciliation and reversal of operational cash flows.',
    'card_realized_title': 'Realized Cash Flow',
    'card_realized_subtitle':
        'Summary of posted and reconciled transactions for the selected period.',
    'transactions_title': 'Transactions',
    'transactions_empty': 'No transactions for the selected filters.',
    'transaction_new': 'New transaction',
    'transaction_edit': 'Edit draft',
    'transaction_detail': 'Transaction details',
    'transaction_code': 'Transaction code',
    'transaction_date': 'Transaction date',
    'value_date': 'Value date',
    'amount': 'Amount',
    'direction': 'Direction',
    'direction_inflow': 'Inflow',
    'direction_outflow': 'Outflow',
    'status': 'Status',
    'tx_status_draft': 'Draft',
    'tx_status_planned': 'Planned',
    'tx_status_posted': 'Posted',
    'tx_status_reconciled': 'Reconciled',
    'tx_status_cancelled': 'Cancelled',
    'description': 'Description',
    'reference': 'Reference',
    'filter_status': 'Status',
    'filter_account': 'Account',
    'filter_direction': 'Direction',
    'filter_period': 'Period',
    'filter_all': 'All',
    'filter_all_accounts': 'All accounts',
    'date_from': 'Date from',
    'date_to': 'Date to',
    'account': 'Account',
    'category': 'Category',
    'post_transaction': 'Post',
    'post_transaction_confirm':
        'Posting changes the account balance. Continue?',
    'reconcile_transaction': 'Reconcile',
    'reconcile_transaction_confirm':
        'Reconciliation does not change the account balance. Continue?',
    'reverse_transaction': 'Reverse',
    'reverse_transaction_confirm':
        'Reversal creates a new transaction in the opposite direction. The original remains in history. Continue?',
    'cancel_draft': 'Cancel draft',
    'cancel_draft_confirm':
        'The draft will be cancelled without changing the balance. Continue?',
    'posted': 'Posted.',
    'reconciled': 'Reconciled.',
    'reversed': 'Reversal completed.',
    'draft_cancelled': 'Draft cancelled.',
    'audit_section': 'Audit trail',
    'audit_created_by': 'Created by',
    'audit_posted_by': 'Posted by',
    'audit_reconciled_by': 'Reconciled by',
    'audit_posted_at': 'Posted at',
    'audit_reconciled_at': 'Reconciled at',
    'link_reversal': 'Reversal transaction',
    'link_original': 'Original transaction',
    'realized_title': 'Realized Cash Flow',
    'realized_period': 'Period',
    'realized_total_inflows': 'Total inflows',
    'realized_total_outflows': 'Total outflows',
    'realized_net_cash_flow': 'Net cash flow',
    'realized_closing_balance': 'Closing balance',
    'realized_transaction_count': 'Transaction count',
    'realized_by_activity': 'By activity type',
    'realized_inflows': 'Inflows',
    'realized_outflows': 'Outflows',
    'realized_net': 'Net',
    'load_report': 'Load report',
    'select_account': 'Select account',
    'select_category': 'Select category',
    'select_direction': 'Select direction',
    'invoices_hub_subtitle':
        'Invoices, receivables and payables — Callable layer (P2).',
    'card_sales_invoices_title': 'Sales invoices',
    'card_sales_invoices_subtitle':
        'Drafts, issue and receivables per invoice.',
    'card_purchase_invoices_title': 'Purchase invoices',
    'card_purchase_invoices_subtitle':
        'Drafts, approval and payables per invoice.',
    'card_receivables_title': 'Receivables',
    'card_receivables_subtitle':
        'Open and partially paid sales invoices.',
    'card_payables_title': 'Payables',
    'card_payables_subtitle':
        'Open and partially paid purchase invoices.',
    'sales_invoices_title': 'Sales invoices',
    'sales_invoices_empty': 'No sales invoices.',
    'sales_invoice_new': 'New sales invoice',
    'sales_invoice_edit': 'Edit sales invoice draft',
    'purchase_invoices_title': 'Purchase invoices',
    'purchase_invoices_empty': 'No purchase invoices.',
    'purchase_invoice_new': 'New purchase invoice',
    'purchase_invoice_edit': 'Edit purchase invoice draft',
    'receivables_title': 'Receivables',
    'receivables_empty': 'No open receivables.',
    'receivables_open_list': 'Open and partially paid invoices',
    'payables_title': 'Payables',
    'payables_empty': 'No open payables.',
    'payables_open_list': 'Open and partially paid obligations',
    'customer_id': 'Customer code',
    'customer_name': 'Customer',
    'supplier_id': 'Supplier code',
    'supplier_name': 'Supplier',
    'net_amount': 'Net amount',
    'tax_amount': 'Tax amount',
    'total_amount': 'Total amount',
    'paid_amount': 'Paid',
    'open_amount': 'Open',
    'issue_date': 'Issue date',
    'due_date': 'Due date',
    'issue_sales_invoice': 'Issue invoice',
    'approve_purchase_invoice': 'Approve invoice',
    'cancel_invoice': 'Cancel invoice',
    'cancel_invoice_confirm':
        'The invoice will be cancelled per backend lifecycle rules. Continue?',
    'invoice_issued': 'Invoice issued.',
    'invoice_approved': 'Invoice approved.',
    'invoice_cancelled': 'Invoice cancelled.',
    'invoice_overdue': 'Overdue',
    'invoice_erp_synced': 'ERP',
    'invoice_erp_readonly_hint':
        'ERP-synced invoice: ERP-owned fields are not editable.',
    'open_items_count': 'Open invoice count',
    'open_items_total': 'Total open amount',
    'open_items_overdue_count': 'Overdue invoice count',
    'open_items_overdue_amount': 'Overdue amount',
    'inv_status_draft': 'Draft',
    'inv_status_open': 'Open',
    'inv_status_partial': 'Partially paid',
    'inv_status_paid': 'Paid',
    'inv_status_cancelled': 'Cancelled',
    'allocate_to_invoices': 'Allocate to invoices',
    'allocated_amount': 'Allocated',
    'unallocated_amount': 'Unallocated',
    'payment_allocations_section': 'Payment allocations',
    'allocations_empty': 'No allocations.',
    'allocations_active_total': 'Total actively allocated',
    'allocation_add_invoice': 'Add invoice',
    'allocation_lines_empty': 'Add one or more invoices to allocate.',
    'allocation_line_amount': 'Allocation amount',
    'allocation_invoice_remaining': 'Remaining open invoice amount',
    'allocation_batch_total': 'Allocation batch total',
    'allocation_remaining_tx': 'Remaining unallocated transaction amount',
    'allocation_confirm': 'Confirm allocation',
    'allocation_saved': 'Allocation saved.',
    'allocation_no_invoices': 'No matching open invoices.',
    'allocation_pick_sales_invoice': 'Select sales invoice',
    'allocation_pick_purchase_invoice': 'Select purchase invoice',
    'allocation_exceeds_unallocated':
        'Allocation total exceeds available unallocated amount.',
    'allocation_amount_required': 'Enter an allocation amount.',
    'allocation_amount_decimals': 'At most two decimal places.',
    'allocation_amount_invalid': 'Amount must be positive.',
    'allocation_cancel': 'Cancel allocation',
    'allocation_cancel_confirm': 'Cancel',
    'allocation_cancel_warning':
        'The account balance will not change. The invoice will regain its open amount. The original Cash Flow transaction remains posted. The allocation stays in history as cancelled.',
    'allocation_cancel_reason': 'Cancellation reason',
    'allocation_cancelled': 'Allocation cancelled.',
    'allocation_status_active': 'Active',
    'allocation_status_cancelled': 'Cancelled',
    'allocation_allocated_by': 'Allocated by',
    'allocation_allocated_at': 'Allocation date',
    'allocation_cancelled_at': 'Cancelled at',
    'allocation_cancelled_by': 'Cancelled by',
    'invoice_number': 'Invoice number',
  };
}
